### ISSUE TITLE
'OpenAPIConverter' object has no attribute 'resolve_schema_class'

### ISSUE THREAD

**Issue by mahenzon** [AdCombo/combojsonapi#19]
Happens with apispec 4.0.0 (was installed automatically)
Fastest: pin/freeze apispec version (works with 2.0.2)
Best: update compatibility

Full traceback:
```
Traceback (most recent call last):
  File "app.py", line 105, in <module>
    json_api.route(views.PersonList, "person_list", "/api/person/", tag="Person")
  File "/usr/local/lib/python3.7/site-packages/flask_combo_jsonapi/api.py", line 111, in route
    i_plugin.after_route(resource=resource, view=view, urls=urls, self_json_api=self, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/combojsonapi/spec/plugin.py", line 114, in after_route
    self._add_definitions_in_spec(resource.schema)
  File "/usr/local/lib/python3.7/site-packages/combojsonapi/spec/plugin.py", line 444, in _add_definitions_in_spec
    self.spec.components.schema(name_schema, schema=schema)
  File "/usr/local/lib/python3.7/site-packages/apispec/core.py", line 82, in schema
    ret.update(plugin.schema_helper(name, component, **kwargs) or {})
  File "/usr/local/lib/python3.7/site-packages/apispec/ext/marshmallow/__init__.py", line 164, in schema_helper
    json_schema = self.converter.schema2jsonschema(schema_instance)
  File "/usr/local/lib/python3.7/site-packages/apispec/ext/marshmallow/openapi.py", line 175, in schema2jsonschema
    jsonschema = self.fields2jsonschema(fields, partial=partial, ordered=ordered)
  File "/usr/local/lib/python3.7/site-packages/apispec/ext/marshmallow/openapi.py", line 199, in fields2jsonschema
    prop = self.field2property(field_obj)
  File "/usr/local/lib/python3.7/site-packages/apispec/ext/marshmallow/field_converter.py", line 161, in field2property
    ret.update(attr_func(field, ret=ret))
  File "/usr/local/lib/python3.7/site-packages/apispec/ext/marshmallow/field_converter.py", line 417, in nested2properties
    schema_dict = self.resolve_nested_schema(field.schema)
  File "/usr/local/lib/python3.7/site-packages/combojsonapi/spec/plugin.py", line 478, in resolve_nested_schema
    schema_cls = self.resolve_schema_class(schema)
AttributeError: 'OpenAPIConverter' object has no attribute 'resolve_schema_class'
```

**Comment by mahenzon** [comment]
closed in #33
